### PR TITLE
Feat/cache

### PR DESCRIPTION
**Pull request by manolakis**
Adds a cache to improve performance and return always the same processed strings reference

### CODE REVIEW

**Comment by bashmish** [comment]
Numbers look super promising! I see a performance boost by an order which I expected theoretically and which corresponds better with the numbers where static tag names are used, while my PR https://github.com/bashmish/carehtml/pull/6 gives just 2x better results.

I'm not sure why this is happening, would be happy to learn what you think made the biggest impact. But all tests still pass and numbers give confidence.

- creating

image

- creating + rendering (most important, because measures whether lit-html detects whether the same template is used)

image

Do you mind if I fix a few nitpicks myself in your branch before merging a releasing?

**Comment by manolakis** [comment]
> I'm not sure why this is happening, would be happy to learn what you think made the biggest impact. But all tests still pass and numbers give confidence.

Running the Polymer benchmark my cache implementation is slightly slower than yours (between 0% - 2%), so I think it depends on the test. My feeling is that if some component are reused or interacted a lot, like for example rows in a table, then my cache fits better, but if the app is composed by components that are used just once then yours performs better than mine, although I "think" (I don't have numbers) that in memory consumption mine is better because of the use of the WeakMap, so the garbage collector can do it's job over the cached items.

> Do you mind if I fix a few nitpicks myself in your branch before merging a releasing?

Sure, no problem.

**Comment by manolakis** [comment]
```bash
┌─────────────┬──────────────┐
│     Version │ <none>       │
├─────────────┼──────────────┤
│     Browser │ chrome       │
│             │ 79.0.3945.79 │
├─────────────┼──────────────┤
│ Sample size │ 270          │
└─────────────┴──────────────┘

┌─────────────┬────────────┬─────────────────────┬─────────────────┬─────────────────┬─────────────────┐
│ Benchmark   │ Bytes      │            Avg time │  vs lit-element │     vs carehtml │  vs auto-define │
├─────────────┼────────────┼─────────────────────┼─────────────────┼─────────────────┼─────────────────┤
│ lit-element │ 182.48 KiB │ 109.58ms - 111.37ms │                 │          faster │          faster │
│             │            │                     │        -        │         1% - 3% │         2% - 4% │
│             │            │                     │                 │ 0.95ms - 3.41ms │  2.33ms - 4.8ms │
├─────────────┼────────────┼─────────────────────┼─────────────────┼─────────────────┼─────────────────┤
│ carehtml    │ 188.26 KiB │ 111.82ms - 113.50ms │          slower │                 │          faster │
│             │            │                     │         1% - 3% │        -        │         0% - 2% │
│             │            │                     │ 0.95ms - 3.41ms │                 │ 0.18ms - 2.58ms │
├─────────────┼────────────┼─────────────────────┼─────────────────┼─────────────────┼─────────────────┤
│ auto-define │ 188.43 KiB │ 113.19ms - 114.89ms │          slower │          slower │                 │
│             │            │                     │         2% - 4% │         0% - 2% │        -        │
│             │            │                     │ 2.33ms - 4.80ms │ 0.18ms - 2.58ms │                 │
└─────────────┴────────────┴─────────────────────┴─────────────────┴─────────────────┴─────────────────┘

``` 

What it look promising is that we are talking about ms.

**Comment by bashmish** [comment]
@manolakis then can you please "Allow edits from maintainers" for this PR branch?

https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork

**Comment by manolakis** [comment]
It's checked

**Comment by c-dinkel** [comment]
@bashmish was this ever merged? If not, shall I copy all the changes into a new pull request?

**Comment by bashmish** [comment]
@c-dinkel it needs a bit of history to explain. Let me try.

I was highly motivated with the idea of having a simple declarative API for writing dynamic templates which resulted in the "carehtml" project. And I had my own implementation of cache in the works (I still have a code with some perf tests even), while folks at Open WC wanted to use some of this and build a different API. @manolakis did quite some work here first, but then switched to the Open WC and implemented a different API there with cache and other interesting things. It resulted in this package: https://github.com/open-wc/open-wc/tree/master/packages/scoped-elements, I encourage you to take a look. So the change in this project was not so anticipated anymore.

Given I could not convince Open WC folks to go with my API, I decided to let it go. At the same time I almost stopped working with web components and lost motivation to work on this project.

But now I'm a bit bored (and still excited about web components), so I might rethink this decision. Especially seeing that there are people who are using it. But I had a different vision on the caching as compared to this PR, so I'd rather prefer not to just reopen this and maybe continue with the code I had back then. It's not necessarily faster, but I believe it's a better fit in the architecture of this project and such a core foundation I'd prefer to build myself.

Please let me know how interested you are in the continuation of this project. Most likely finishing what I had back then would not be too much work.

**Comment by bashmish** [comment]
Found an old branch of mine: https://github.com/bashmish/carehtml/tree/feat/cache (most likely it's incomplete).

And I have a few local stashes with benchmarks which I used on both this PR and my implementation. Would be nice move them to my branch and have it finished.

**Comment by c-dinkel** [comment]
@bashmish thank you very much for your extensive feedback ad insight! ❤️ 

> Given I could not convince Open WC folks to go with my API, I decided to let it go. At the same time I almost stopped working with web components and lost motivation to work on this project.

`carehtml` actually covers a different (i.e. our) use case than `scoped-elements`. We actually cannot know statically at instantiation time of our WebComponent which - or even how many - other WebComponents we will be using, since we use them at runtime. So dynamic generation of tag names at use time is absolutely vital for us. `open-wc`'s proposal does not address this requirement.

> But now I'm a bit bored (and still excited about web components), so I might rethink this decision. Especially seeing that there are people who are using it. But I had a different vision on the caching as compared to this PR, so I'd rather prefer not to just reopen this and maybe continue with the code I had back then. It's not necessarily faster, but I believe it's a better fit in the architecture of this project and such a core foundation I'd prefer to build myself.
> 
> Please let me know how interested you are in the continuation of this project. Most likely finishing what I had back then would not be too much work.

That is great to hear. We have the very highest interest in this project being continued and actively maintained! This is currently the only readily-available solution for our above-stated requirement, so our plugin system relies entirely on its availability. Should this project be finally discontinued, we would have no choice but to maintain a fork.

I am personally very thankful for your contributing this great library to the open source ecosystem.

PS: Maybe this discussion is best continued in #9 ?

**Comment by bashmish** [comment]
@c-dinkel thanks for using the project, that's great to hear it has nice use-cases. We can discuss #9 there and I'm planning to finish my work on the cache over the weekend and to open another PR for it.

**Pull request closed without merging**
